*
***************************************************
*   OPTION SWITCHES
***************************************************
*
*
** THE CONTROL PORT CAN ONLY BE ONE OF THESE
** NOTE THAT THE ACIA WILL ALWAYS BE PRESET
** FOR LOADING AND SAVING S1 RECORDS
*
*SWTOPT EQU $FF SWTP ACIA SERIAL CONTROL PORT
*ADSOPT EQU $FF ADS6809 & DG640 VIDEO DISPAY
*B3SOPT EQU $FF B3-SPARTAN2 FPGA VIDEO & PS2 KEYBOARD
*B5XOPT EQU $FF B5-X300 FPGA VIDEO & PS2 KEYBOARD
*S3SOPT EQU $FF SPARTAN3 STARTER FPGA VIDEO & PS2 KEYBOARD
S3EOPT EQU $FF SPARTAN3E STARTER
*XESOPT EQU $FF XESS XSA-3S100 & XST-3.0
*
 END
